#!/bin/bash

# This script allows to clone and compile rflpc so that it can be used to
# compile smews
# 
# Author: Michael Hauspie <michael.hauspie@univ-lille1.fr>
# Created: 
# Time-stamp: <2012-05-16 14:48:37 (hauspie)>
#

RFLPC_REPOSITORY="git://github.com/hauspie/rflpc.git"
RFLPC_RELEASE="v0.9"
LOCAL_FOLDER="`cd \`dirname $0\` && pwd`"
RFLPC_FOLDER=$LOCAL_FOLDER/rflpc
RFLPC_CONFIG_FILE_SRC=$LOCAL_FOLDER/rflpc-config-file/config-options.h
RFLPC_CONFIG_FOLDER=$RFLPC_FOLDER/rflpc17xx/config

if [ -d $RFLPC_FOLDER ]
then
    cd $RFLPC_FOLDER
    if ! git fetch
    then
	echo "Failed to update rflpc" 1>&2
	exit 1
    fi
else
    if ! git clone $RFLPC_REPOSITORY $RFLPC_FOLDER
    then
	echo "Failed to clone rflpc repository. Do you have git installed?" 1>&2
	exit 1
    fi
    cd $RFLPC_FOLDER
fi

git checkout -B $RFLPC_RELEASE

TMP_LOG_FILE=`mktemp`
echo "Compiling library"
make mrproper >& /dev/null
# Creating config file
cp $RFLPC_CONFIG_FILE_SRC $RFLPC_CONFIG_FOLDER
# Compile
if ! make -C rflpc17xx >& $TMP_LOG_FILE
then
    cat $TMP_LOG_FILE 1>&2
    echo "Failed to compile rflpc!" 1>&2
    rm -f $TMP_LOG_FILE
    exit 1
fi
rm -rf $TMP_LOG_FILE
echo "rflpc successfuly compiled"
