all: targets

targets:
	@cd AVR; make;
	@cd MSP430; make;
	@cd linux; make;

size:
	@cd AVR; make size;
	@cd MSP430; make size;
	@cd linux; make size;

clean:
	@cd AVR; make clean;
	@cd MSP430; make clean;
	@cd linux; make clean;

