import os
import os.path

libname = os.path.basename(os.path.abspath(os.curdir))

VariantDir('bin', 'src',duplicate=0)
env = Environment()
env.Append(CCFLAGS =  '-g -O0 -Wall')
env.Append(CPPPATH = ['../../src/'])
env.Append(CPPPATH = ['/usr/include/PCSC'])
env.Append(LIBS = 'pcsclite')
env.SharedLibrary(libname, Glob('*.c'))
